package com.example.ui.screens

object Localization {
    fun get(key: String, lang: String): String {
        val strings = translations[lang] ?: translations["id"] ?: translations["en"] ?: emptyMap()
        return strings[key] ?: key
    }

    private val translations = mapOf(
        "id" to mapOf(
            "app_title" to "FinAct AI",
            "app_subtitle" to "Asisten Finansial & Aktivitas Interaktif",
            "hello" to "Halo, %s",
            "sandbox_local" to "Sandbox Lokal",
            "cloud_synced" to "Sinkron Cloud",
            "voice_active" to "Suara Aktif",
            "search_active" to "Pencarian Aktif",
            
            // Tabs
            "tab_ledger" to "Buku Kas",
            "tab_planner" to "Rencana",
            "tab_chat" to "Chat AI",
            "tab_insights" to "Analisis",
            "tab_profile" to "Profil",

            // Ledger Screen
            "add_transaction_title" to "Catat Transaksi Manual",
            "merchant_label" to "Nama Toko / Penerima",
            "amount_label" to "Jumlah (Rp)",
            "category_label" to "Kategori",
            "payment_method_label" to "Metode Pembayaran",
            "note_label" to "Catatan / Detail",
            "dynamic_attrs" to "Atribut Kustom Dinamis",
            "add_custom_field" to "Tambah Atribut Kustom",
            "attr_name_placeholder" to "Nama Atribut (misal: Tips, Pajak, Lokasi)",
            "save_transaction" to "Simpan Transaksi",
            "manage_categories_title" to "Kelola Kategori Kustom",
            "create_cat_sub" to "Buat Kategori / Subkategori Kustom",
            "new_cat_name" to "Nama Kategori Baru",
            "parent_cat_optional" to "Kategori Induk (Opsional - Untuk Subkategori)",
            "none_parent_option" to "Tidak Ada (Jadikan Kategori Utama)",
            "create_cat_button" to "Buat Kategori",
            "your_custom_cats" to "Kategori Kustom Anda",
            "main_category" to "Kategori Utama",
            "subcategory_of" to "Subkategori dari: %s",
            "recurring_title" to "Anggaran & Rencana Rutin",
            "recurring_subtitle" to "Otomatisasi Pengeluaran Berulang",
            "recurring_merchant" to "Merchant / Layanan",
            "recurring_amount" to "Jumlah (Rp)",
            "recurring_note" to "Catatan / Keterangan",
            "recurring_button" to "Jadwalkan Rencana Rutin",
            "active_schedules" to "Jadwal Aktif",
            "recent_transactions" to "Riwayat Transaksi Terakhir",
            "no_transactions" to "Belum ada transaksi. Tambah transaksi manual atau lewat Chat AI!",
            
            // Planner Screen
            "schedule_new_event" to "Jadwalkan Aktivitas Baru",
            "event_description" to "Deskripsi Aktivitas",
            "context_mood" to "Konteks / Mood (misal: Stres, Lelah)",
            "duration" to "Durasi (menit)",
            "activity_type" to "Tipe Aktivitas: %s",
            "schedule_activity" to "Jadwalkan Aktivitas",
            "planner_timeline" to "Linimasa Rencana",
            "no_schedules" to "Belum ada jadwal. Bicara alami dengan Gemini untuk menambah tugas (misal: \"Besok jam 9 pagi ada janji temu...\") atau gunakan formulir di atas!",
            
            // Analytics Screen
            "scenario_planner_title" to "Perencana Skenario Interaktif 'What-If'",
            "scenario_subtitle" to "Simulasikan keputusan keuangan masa depan Anda",
            "savings_goal_title" to "Tujuan Tabungan",
            "target_saving" to "Target Tabungan (Rp)",
            "time_horizon" to "Waktu Horizon (Bulan)",
            "monthly_savings_budget" to "Anggaran Tabungan Bulanan (Rp)",
            "scenario_strategy" to "Skenario / Strategi Penghematan",
            "scenario_status_quo" to "Status Quo (Tanpa Perubahan)",
            "scenario_moderate" to "Hemat Moderat (Potong Kopi/Hiburan 20%)",
            "scenario_aggressive" to "Hemat Agresif (Potong Makan Luar/Gaya Hidup 45%)",
            "standard_time_to_goal" to "Waktu Standar ke Target:",
            "with_scenario_time" to "Waktu Skenario Baru:",
            "months_format" to "%.1f bulan",
            "goal_delay_warning" to "⚠️ Peringatan: Anggaran Anda saat ini tidak cukup untuk mencapai tujuan dalam jangka waktu target. Target Anda tertunda %.1f bulan.",
            "goal_acceleration_success" to "🎉 Skenario ini mempercepat pencapaian target Anda %.1f bulan lebih cepat!",
            "ai_financial_insights" to "Wawasan Gaya Hidup & Keuangan AI",
            "refresh_insights_btn" to "Segarkan Analisis AI Gemini",

            // Settings / Profile Screen
            "ai_settings_title" to "Pengaturan Asisten AI",
            "slang_style_title" to "Gaya Bahasa & Percakapan",
            "slang_subtitle" to "Ubah cara Gemini berbicara, beradaptasi, dan terhubung dengan Anda.",
            "conversational_slang_label" to "Gaya Bahasa (misal: Santai, Gaul Jakarta, Formal)",
            "update_style_btn" to "Perbarui Gaya Kepribadian",
            "stored_memory" to "Profil Memori Jangka Panjang AI",
            "stored_memory_subtitle" to "Sesuaikan informasi yang diingat Gemini tentang kebiasaan jangka panjang Anda.",
            "ai_memory_label" to "Item Memori Permanen AI",
            "save_memories_btn" to "Simpan Memori",
            "purge_consolidate_btn" to "Konsolidasi Mingguan",
            "firebase_sync_title" to "Panduan Sinkronisasi Cloud Firebase",
            "firebase_sync_body" to "Aplikasi ini terintegrasi dengan Google Sign-In, Firebase Auth, dan Firestore. Saat berjalan dalam mode Sandbox, semua fitur offline-first Room berjalan penuh.\n\nUntuk menyinkronkan data dengan Firestore di produksi:\n1. Unduh 'google-services.json' dari Firebase Console Anda.\n2. Letakkan di dalam folder '/app' dari proyek ini dan bangun kembali.",
            "logout_btn" to "Keluar Akun",

            // Language settings card
            "language_settings_title" to "Pengaturan Bahasa (Language Settings)",
            "language_settings_subtitle" to "Pilih bahasa tampilan untuk seluruh aplikasi ini.",
            "language_id" to "Bahasa Indonesia",
            "language_en" to "English (Inggris)",

            // Auth Screen
            "auth_welcome" to "Selamat Datang di FinAct AI",
            "auth_sub" to "Asisten Finansial & Aktivitas Interaktif",
            "auth_email" to "Alamat Email",
            "auth_password" to "Kata Sandi",
            "auth_register" to "Buat Akun Baru",
            "auth_login" to "Masuk ke Akun",
            "auth_sign_up" to "Daftar",
            "auth_log_in" to "Masuk",
            "auth_already_have_account" to "Sudah punya akun? Masuk",
            "auth_new_user" to "Pengguna baru? Buat akun",
            "auth_sign_in_google" to "Masuk dengan Google",
            "auth_offline_sandbox" to "Mulai dalam Mode Sandbox Lokal Offline-First →",

            // Chat Screen
            "chat_active_listening" to "Gemini sedang mendengarkan...",
            "chat_type_message" to "Ketik pesan untuk mencatat keuangan atau aktivitas...",
            "tts_toggle_label" to "Aktifkan Balasan Suara TTS",
            "grounding_toggle_label" to "Aktifkan Pencarian Real-time",
            "send" to "Kirim",

            // Newly added for perfect localization
            "morning_briefing_title" to "Sintesis Harian Anda",
            "morning_briefing_desc" to "Membuat Sintesis Harian personal Anda berdasarkan pola jadwal dan anggaran...",
            "morning_briefing_header" to "SINTESIS HARIAN",
            "todays_spend_header" to "PENGELUARAN HARI INI",
            "impulse_risk_header" to "RISIKO IMPULSIF",
            "high" to "Tinggi",
            "medium" to "Sedang",
            "low" to "Rendah",
            "thinking" to "Berpikir...",
            "tts_label" to "Balasan Suara (TTS)",
            "google_search_label" to "Pencarian Google",
            "quick_sugg_coffee" to "Beli kopi Rp 18rb",
            "quick_sugg_coffee_full" to "Beli kopi Rp 18rb di Kopi Kenangan",
            "quick_sugg_thesis" to "Tugas bimbingan skripsi",
            "quick_sugg_thesis_full" to "Besok jam 9 pagi bimbingan skripsi dengan dosen",
            "chat_placeholder" to "Catat keuangan atau rencana lewat chat...",
            "model_hypo_title" to "Simulasi Peristiwa Finansial Hipotetis",
            "select_scenario" to "Pilih Skenario",
            "scenario_amount" to "Jumlah Skenario (Rp)",
            "interest_rate" to "Tingkat Bunga Tahunan (%)",
            "timeline_horizon" to "Waktu Horizon: %d Bulan",
            "evaluate_goal" to "Evaluasi Kemajuan Target",
            "projected_results" to "Proyeksi Hasil Skenario",
            "monthly_budget_shift" to "Perubahan Anggaran Bulanan",
            "status_quo_savings" to "Tabungan Status Quo",
            "scenario_savings" to "Tabungan Skenario",
            "over_months" to "Selama %d Bulan",
            "goal_impact" to "🚀 Dampak Lini Masa Target: %s",
            "standard_time_to_goal_label" to "Waktu Standar ke Target:",
            "with_scenario_time_label" to "Waktu Skenario Baru:",
            "faster_format" to "Mencapai target Anda %s bulan LEBIH CEPAT! 🎉",
            "slower_format" to "Menunda pencapaian target Anda selama %s bulan.",
            "behavioral_analytics" to "Analisis Perilaku Gaya Hidup",
            "analyze_button" to "Analisis",
            "unified_insights_model" to "Model Wawasan Terpadu Gemini"
        ),
        "en" to mapOf(
            "app_title" to "FinAct AI",
            "app_subtitle" to "Conversational Finance & Activity Coach",
            "hello" to "Hello, %s",
            "sandbox_local" to "Sandbox Local",
            "cloud_synced" to "Cloud Synced",
            "voice_active" to "Voice Active",
            "search_active" to "Search Active",
            
            // Tabs
            "tab_ledger" to "Ledger",
            "tab_planner" to "Planner",
            "tab_chat" to "Chat AI",
            "tab_insights" to "Insights",
            "tab_profile" to "Profile",

            // Ledger Screen
            "add_transaction_title" to "Add Manual Transaction",
            "merchant_label" to "Merchant / Recipient",
            "amount_label" to "Amount (Rp)",
            "category_label" to "Category",
            "payment_method_label" to "Payment Method",
            "note_label" to "Note / Detail",
            "dynamic_attrs" to "Dynamic Custom Attributes",
            "add_custom_field" to "Add Custom Field Attribute",
            "attr_name_placeholder" to "Attribute Name (e.g., Tip, Tax, Location)",
            "save_transaction" to "Save Transaction",
            "manage_categories_title" to "Manage Custom Categories",
            "create_cat_sub" to "Create Custom Category / Subcategory",
            "new_cat_name" to "Category Name",
            "parent_cat_optional" to "Parent Category (Optional - For Subcategories)",
            "none_parent_option" to "None (Make Main Category)",
            "create_cat_button" to "Create Category",
            "your_custom_cats" to "Your Custom Categories",
            "main_category" to "Main Category",
            "subcategory_of" to "Subcategory of: %s",
            "recurring_title" to "Recurring Budgets & Schedules",
            "recurring_subtitle" to "Automate Repeating Expenses",
            "recurring_merchant" to "Merchant / Service",
            "recurring_amount" to "Amount (Rp)",
            "recurring_note" to "Note / Detail",
            "recurring_button" to "Schedule Recurring Plan",
            "active_schedules" to "Active Schedules",
            "recent_transactions" to "Recent Transaction History",
            "no_transactions" to "No transactions yet. Add manually or via Chat AI!",
            
            // Planner Screen
            "schedule_new_event" to "Schedule New Event",
            "event_description" to "Event Description",
            "context_mood" to "Context / Mood (e.g. Stress, Tired)",
            "duration" to "Duration (min)",
            "activity_type" to "Activity Type: %s",
            "schedule_activity" to "Schedule Activity",
            "planner_timeline" to "Planner Timeline",
            "no_schedules" to "No schedules. Chat naturally with Gemini to add tasks (e.g., \"Tomorrow at 9 AM I have appointment with... \") or use the form above!",
            
            // Analytics Screen
            "scenario_planner_title" to "Interactive 'What-If' Scenario Planner",
            "scenario_subtitle" to "Simulate your future financial decisions",
            "savings_goal_title" to "Savings Goal Target",
            "target_saving" to "Savings Goal (Rp)",
            "time_horizon" to "Time Horizon (Months)",
            "monthly_savings_budget" to "Monthly Savings Budget (Rp)",
            "scenario_strategy" to "Scenario / Strategy Strategy",
            "scenario_status_quo" to "Status Quo (No Changes)",
            "scenario_moderate" to "Moderate Savings (Cut Coffee/Fun 20%)",
            "scenario_aggressive" to "Aggressive Savings (Cut Dining/Leisure 45%)",
            "standard_time_to_goal" to "Standard Time to Goal:",
            "with_scenario_time" to "With Scenario Time:",
            "months_format" to "%.1f months",
            "goal_delay_warning" to "⚠️ Alert: Your current budget is not enough to achieve goal within target horizon. Goal delayed by %.1f months.",
            "goal_acceleration_success" to "🎉 This scenario accelerates achieving your goal by %.1f months earlier!",
            "ai_financial_insights" to "AI Lifestyle & Financial Insights",
            "refresh_insights_btn" to "Refresh Gemini AI Insights",

            // Settings / Profile Screen
            "ai_settings_title" to "AI Assistant Settings",
            "slang_style_title" to "Slang & Conversational Style",
            "slang_subtitle" to "Change how Gemini speaks, adapts, and connects with you.",
            "conversational_slang_label" to "Conversational Slang (e.g., Chill, Friendly Jakarta slang, formal)",
            "update_style_btn" to "Update Personality Style",
            "stored_memory" to "Stored Memory Profiles",
            "stored_memory_subtitle" to "Adjust and edit what information Gemini retains about your long-term behaviors.",
            "ai_memory_label" to "AI Permanent Memory Items",
            "save_memories_btn" to "Save Memories",
            "purge_consolidate_btn" to "Purge & Consolidate Weekly",
            "firebase_sync_title" to "Firebase Cloud Sync Guide",
            "firebase_sync_body" to "This app is configured to use Google Sign-In, Firebase Auth, and Firestore. When running locally in Sandbox, offline-first Room features are fully active.\n\nTo synchronize with Firestore in production:\n1. Download 'google-services.json' from your Firebase Console.\n2. Put it inside '/app' folder of this project directory and rebuild.",
            "logout_btn" to "Logout Account",

            // Language settings card
            "language_settings_title" to "Language Settings (Pengaturan Bahasa)",
            "language_settings_subtitle" to "Select display language for the entire application.",
            "language_id" to "Indonesian (Bahasa Indonesia)",
            "language_en" to "English (Inggris)",

            // Auth Screen
            "auth_welcome" to "Welcome to FinAct AI",
            "auth_sub" to "Conversational Finance & Activity Coach",
            "auth_email" to "Email Address",
            "auth_password" to "Password",
            "auth_register" to "Create Account",
            "auth_login" to "Welcome Back",
            "auth_sign_up" to "Sign Up",
            "auth_log_in" to "Log In",
            "auth_already_have_account" to "Already have an account? Log In",
            "auth_new_user" to "New user? Create an account",
            "auth_sign_in_google" to "Sign In with Google",
            "auth_offline_sandbox" to "Launch in Offline-First Local Sandbox Mode →",

            // Chat Screen
            "chat_active_listening" to "Gemini is listening...",
            "chat_type_message" to "Type a message to log finance or activities...",
            "tts_toggle_label" to "Enable TTS Voice Reply",
            "grounding_toggle_label" to "Enable Real-time Search Grounding",
            "send" to "Send",

            // Newly added for perfect localization
            "morning_briefing_title" to "Your Daily Synthesis",
            "morning_briefing_desc" to "Generating your personalized Morning Briefing based on schedule patterns and budgets...",
            "morning_briefing_header" to "MORNING BRIEFING",
            "todays_spend_header" to "TODAY'S SPEND",
            "impulse_risk_header" to "IMPULSE RISK",
            "high" to "High",
            "medium" to "Medium",
            "low" to "Low",
            "thinking" to "Thinking...",
            "tts_label" to "Voice Reply (TTS)",
            "google_search_label" to "Google Search",
            "quick_sugg_coffee" to "Spent Rp 18k on coffee",
            "quick_sugg_coffee_full" to "Spent Rp 18k on coffee at Kopi Kenangan",
            "quick_sugg_thesis" to "Thesis mentoring task",
            "quick_sugg_thesis_full" to "Tomorrow at 9 AM I have thesis mentoring with lecturer",
            "chat_placeholder" to "Log finances or schedules with chat...",
            "model_hypo_title" to "Model Hypothetical Financial Events",
            "select_scenario" to "Select Scenario",
            "scenario_amount" to "Scenario Amount (Rp)",
            "interest_rate" to "Annual Interest Rate (%)",
            "timeline_horizon" to "Timeline Horizon: %d Months",
            "evaluate_goal" to "Evaluate Goal Progress",
            "projected_results" to "Projected Scenario Results",
            "monthly_budget_shift" to "Monthly Budget Shift",
            "status_quo_savings" to "Status Quo Savings",
            "scenario_savings" to "Scenario Savings",
            "over_months" to "Over %d Months",
            "goal_impact" to "🚀 Goal Timeline Impact: %s",
            "standard_time_to_goal_label" to "Standard Time to Goal:",
            "with_scenario_time_label" to "With Scenario Time:",
            "faster_format" to "Reaches your goal %s months FASTER! 🎉",
            "slower_format" to "Delays your goal achievement by %s months.",
            "behavioral_analytics" to "Behavioral Lifestyle Analytics",
            "analyze_button" to "Analyze",
            "unified_insights_model" to "Gemini Unified Insights Model"
        )
    )
}
